CREATE TABLE grid
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time_created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    time_updated      TIMESTAMP WITHOUT TIME ZONE,
    number_of_rows    INTEGER                                 NOT NULL,
    number_of_columns INTEGER                                 NOT NULL,
    CONSTRAINT pk_grid PRIMARY KEY (id)
);


CREATE TABLE cell
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time_created TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    time_updated TIMESTAMP WITHOUT TIME ZONE,
    grid_id      BIGINT                                  NOT NULL,
    row_index    INTEGER                                 NOT NULL,
    column_index INTEGER                                 NOT NULL,
    value        BIGINT                                  NOT NULL,
    effect       SMALLINT,
    CONSTRAINT pk_cell PRIMARY KEY (id)
);

CREATE INDEX cell_column_index ON cell (column_index);

CREATE INDEX cell_row_index ON cell (row_index);
